#!/usr/bin/env bash

source  ./services/_init.sh

./services/run   ${EO_HOST} <<'EOF'
#!/usr/bin/env bash

set -e

command -v systemctl > /dev/null 2>&1 && {
    systemctl   is-active   openvpn@server.service > /dev/null 2>&1   && {
        systemctl   stop    openvpn@server.service
    }
    systemctl   disable     openvpn@server.service
    echo        ----------------------
    systemctl   status      openvpn@server.service      ||  true
}

command -v systemctl > /dev/null 2>&1   || {
    chkconfig   openvpn     off
    service     openvpn     stop
    echo        ----------------------
    service     openvpn     status      ||  true
}

exit    0
EOF
