#!/usr/bin/env bash

source  ./services/_init.sh

./services/run       ${EO_HOST}    <<'EOF'
    set     -e
    command -v      docker  >/dev/null 2>&1 ||  {
        curl    -fsSL   https://get.docker.com/ | sh || true #don't check failure
    }
    command -v      docker  >/dev/null 2>&1 ||  {
        exit    1
    }
    exit    0
EOF

./services/reload     ${EO_HOST}    docker
./services/stop       ${EO_HOST}    docker

./services/update-conf-and-reload    ${EO_HOST}  docker
