#!/usr/bin/env bash

source  ./scripts/_init.sh

CONF_DIR=/etc/docker

for f in daemon.json ; do
    [ -f ${EO_CONF}/docker/${f} ] &&
        ./scripts/sync  ${EO_CONF}/docker/${f}  ${EO_HOST}:${CONF_DIR}/${f}
done

./scripts/reload    ${EO_HOST} docker
