#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run   ${EO_HOST} '
clean_sum=$(docker images | grep "<none>" | wc -l)
if [[ $clean_sum -gt 0 ]]; then
    docker images | grep "<none>" | awk "{ print $3 }" | xargs -r docker rmi
fi
'
