#!/usr/bin/env bash

source  ./scripts/_init.sh

########################################
#   Note: suport CentOS 7 only
########################################

CONF_DIR=/etc/openresty

./scripts/run       ${EO_HOST}    <<'EOF'
    set     -e
    command -v      docker  >/dev/null 2>&1 ||  {
        curl    -fsSL   https://get.docker.com/ | sh || true #don't check failure
    }
    command -v      docker  >/dev/null 2>&1 ||  {
        exit    1
    }
    exit    0
EOF

./scripts/reload     ${EO_HOST}    docker
./scripts/stop       ${EO_HOST}    docker

./scripts/update-conf-and-reload    ${EO_HOST}  docker
