#!/usr/bin/env bash

source  ./scripts/_init.sh

EO_SVC=firewalld

for conf_dir in etc/firewalld ; do
    if [ -d "${EO_CONF}/${EO_SVC}/${conf_dir}" ] ;then
        ./scripts/sync  "${EO_CONF}/${EO_SVC}/${conf_dir}/"  "${EO_HOST}:/${conf_dir}/" \
            --exclude="dummy"
    fi
done
