#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

./scripts/sync  servers/${host}/firewalld/  ${host}:/etc/firewalld

./scripts/firewalld/svc-reload  ${host}
