#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    <<EOF
which systemctl > /dev/null && {
    systemctl   eanble  firewalld.service
    systemctl   status  firewalld.service > /dev/null   && {
        systemctl   reload      firewalld.service
    } || {
        systemctl   start       firewalld.service
    }
}
echo        ----------------------
systemctl   status  firewalld.service
EOF
