#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    <<EOF
#!/usr/bin/env bash

set -e

which systemctl > /dev/null && {
    systemctl   enable  firewalld.service
    systemctl   reload-or-restart   firewalld.service
    echo        ----------------------
    systemctl   status      firewalld.service
}

which systemctl > /dev/null || {
    chkconfig   firewalld   on
    service     firewalld   restart
    echo        ----------------------
    service     firewalld   status
}

exit    0
EOF
