#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run       ${EO_HOST}    <<'EOF'
    set     -e
    command -v      pip >/dev/null 2>&1 ||  {
        yum install -y  python-pip
    }
    command -v      pip >/dev/null 2>&1 ||  {
        exit    1
    }
    exit    0
EOF

./scripts/update        ${EO_HOST}  pip
