#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

[ -f servers/${host}/php-fpm/php.ini ] && ./scripts/sync  servers/${host}/php-fpm/php.ini   ${host}:/etc/

[ -d servers/${host}/php-fpm/php.d ] && ./scripts/sync  servers/${host}/php-fpm/php.d/   ${host}:/etc/php.d/

[ -d servers/${host}/php-fpm/php-zts.d ] && ./scripts/sync  servers/${host}/php-fpm/php-zts.d/   ${host}:/etc/-zts.d/

[ -f servers/${host}/php-fpm/php-fpm.conf ] && ./scripts/sync  servers/${host}/php-fpm/php-fpm.conf   ${host}:/etc/

[ -d servers/${host}/php-fpm/php-fpm.d ] && ./scripts/sync  servers/${host}/php-fpm/php-fpm.d/   ${host}:/etc/php-fpm.d/

./scripts/reload    ${host} php-fpm
