#!/usr/bin/env bash

source  ./scripts/_init.sh

[ -f ${EO_CONF}/php-fpm/php.ini ] && ./scripts/sync  ${EO_CONF}/php-fpm/php.ini   ${EO_HOST}:/etc/

[ -d ${EO_CONF}/php-fpm/php.d ] && ./scripts/sync  ${EO_CONF}/php-fpm/php.d/   ${EO_HOST}:/etc/php.d/

[ -d ${EO_CONF}/php-fpm/php-zts.d ] && ./scripts/sync  ${EO_CONF}/php-fpm/php-zts.d/   ${EO_HOST}:/etc/-zts.d/

[ -f ${EO_CONF}/php-fpm/php-fpm.conf ] && ./scripts/sync  ${EO_CONF}/php-fpm/php-fpm.conf   ${EO_HOST}:/etc/

[ -d ${EO_CONF}/php-fpm/php-fpm.d ] && ./scripts/sync  ${EO_CONF}/php-fpm/php-fpm.d/   ${EO_HOST}:/etc/php-fpm.d/

./scripts/reload    ${EO_HOST} php-fpm
