#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/php-fpm/repo-install  ${EO_HOST}

if [ -z "${1}" ]; then
    ./scripts/php-fpm/pkg-install   ${EO_HOST} php-fpm  php-opcache
else
    ./scripts/php-fpm/pkg-install   ${EO_HOST} $@
fi

./scripts/php-fpm/conf-update   ${EO_HOST}
