#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    <<EOF
which systemctl > /dev/null && {
    systemctl   enable  php-fpm.service
    systemctl   status  php-fpm.service > /dev/null   && {
        systemctl   reload      php-fpm.service
    } || {
        systemctl   start       php-fpm.service
    }
}
echo        ----------------------
systemctl   status  php-fpm.service
EOF
