#!/usr/bin/env bash

source  ./scripts/_init.sh

EO_SVC=crond

for conf_file in etc/crontab etc/cron.allow etc/cron.deny etc/anacrontab ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./scripts/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done

for conf_dir in etc/cron.d etc/cron.hourly etc/cron.daily etc/cron.weekly etc/cron.monthly ; do
    if [ -d "${EO_CONF}/${EO_SVC}/${conf_dir}" ] ;then
        ./scripts/sync  "${EO_CONF}/${EO_SVC}/${conf_dir}/"  "${EO_HOST}:/${conf_dir}/" \
            --exclude="dummy"                   \
            --exclude="0hourly"                 \
            --exclude="0anacron"                \
            --exclude="logrotate"               \
            --exclude="man-db.cron"
    fi
done

for conf_dir in var/spool/cron ; do
    if [ -d "${EO_CONF}/${EO_SVC}/${conf_dir}" ] ;then
        ./scripts/sync  "${EO_CONF}/${EO_SVC}/${conf_dir}/"  "${EO_HOST}:/${conf_dir}/" \
            --exclude="dummy"
    fi
done

./scripts/reload    ${EO_HOST} crond
