#!/usr/bin/env bash

source  ./scripts/_init.sh

for item in crontab cron.allow cron.deny anacrontab ; do
    [ -f ${EO_CONF}/etc/crontab ] &&
        ./scripts/sync  ${EO_CONF}/crond/etc/$item  ${EO_HOST}:/etc/$item
done

for item in cron.d cron.hourly cron.daily cron.weekly cron.monthly ; do
    [ -d ${EO_CONF}/etc/crontab ] &&
        ./scripts/sync  ${EO_CONF}/crond/etc/$item ${EO_HOST}:/etc/$item \
            --exclude="0hourly"                 \
            --exclude="0anacron"                \
            --exclude="logrotate"               \
            --exclude="man-db.cron"
done

[ -d ${EO_CONF}/cron ] &&
    ./scripts/sync  ${EO_CONF}/crond/cron ${EO_HOST}:/var/spool/cron/

./scripts/reload    ${EO_HOST} crond
