#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run   ${EO_HOST}  <<EOF
#!/usr/bin/env bash

set -e

yum list installed  crontabs   >/dev/null 2>&1  ||   yum     install -y  crontabs cronie cronie-anacron

exit    0
EOF

./scripts/update-conf-and-reload    ${EO_HOST}  crond
