#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    <<EOF
#!/usr/bin/env bash

set -e

which systemctl > /dev/null && {
    systemctl   is-active  crond.service > /dev/null   && {
        systemctl   stop    crond.service
    }
    systemctl   disable  crond.service
    echo        ----------------------
    systemctl   status  crond.service
}

which systemctl > /dev/null || {
    chkconfig   crond    off
    service     crond    stop
    echo        ----------------------
    service     crond    status
}

exit    0
EOF
