#!/usr/bin/env bash

source  ./scripts/_init.sh

EO_SVC=lvm

for conf_file in etc/lvm.conf etc/lvmlocal.conf ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./scripts/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done
