#!/usr/bin/env bash

source  ./services/_init.sh

./services/run   ${EO_HOST}  'rpm -q supervisor >/dev/null 2>&1 || yum install -y  supervisor'

./services/update-conf-and-reload    ${EO_HOST}  supervisord
