#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

./scripts/sync  servers/${host}/etc/hosts.allow     ${host}:/etc/
./scripts/sync  servers/${host}/etc/hosts.deny      ${host}:/etc/
