#!/usr/bin/env bash

group=$(dirname $0)
host=${1}
shift

[ -z "${host}" ]    &&  host=host.example
[ -d "${group}/${host}" ] || {
    echo    "ERROR: [${group}/${host}] not found"
    exit    1
}

svcs=($@)
[ -z "${svcs}" ]    &&  svcs=(crond docker firewalld iptables logrotate ntpd openresty php-fpm rsyslog sshd yum)

pushd  "${group}/${host}"
    for item in ${svcs[@]} ; do
        #echo    "${item}"
        [ -e "${item}" ]    ||    ln  -s  etc     "${item}"
    done
popd
