#!/usr/bin/env bash

host=${1}
shift

svcs=$@
[ -z "${svcs}" ]    &&  svcs=(crond docker firewalld iptables ntpd openresty php-fpm sshd)

pushd  $(dirname $0)/${1}
for item in ${svcs} ; do
    [ ! -e ${item} ]    ||    ln  -s  etc     ${item}
done
popd
