#!/usr/bin/env bash

set -e

if [ "${2}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
    svc=${1}
else
    host=${1}
    svc=${2}
fi

if [ -x scripts/${svc}/svc-reload ] ; then
    scripts/${svc}/svc-reload   ${host}
else
    ssh     ${host}    <<EOF
#!/usr/bin/env bash

set -e

which systemctl > /dev/null 2>&1 && {
    systemctl is-enabled ${svc}.service > /dev/null 2>&1    || {
        systemctl   enable              ${svc}.service
    }
    systemctl is-active ${svc}.service > /dev/null 2>&1     && {
        systemctl   reload-or-restart   ${svc}.service
    }   ||  {
        systemctl   start               ${svc}.service
    }
    echo        ----------------------
    systemctl   status                  ${svc}.service
}
which systemctl > /dev/null 2>&1 || {
    chkconfig   ${svc}      on
    service     ${svc}      reload
    echo        ----------------------
    service     ${svc}      status
}

exit    0
EOF
fi
