#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

INSTALL_ROOT=/home/git

./scripts/sync  servers/${host}/gogs/custom/     ${host}:${INSTALL_ROOT}/gogs/custom/

ssh     ${host}    <<EOF
which systemctl > /dev/null 2>&1 && {
    systemctl   enable  ${INSTALL_ROOT}/gogs/scripts/systemd/gogs.service
}
which systemctl > /dev/null 2>&1 || {
    cp          -f      ${INSTALL_ROOT}/gogs/scripts/init/centos/gogs  /etc/init.d/
    chomod      755     /etc/init.d/gogs
}
EOF

./scripts/svc/reload    ${host} gogs
