#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

INSTALL_ROOT=/home/git

ssh     ${host}    "rm  -rf ${INSTALL_ROOT}/gogs/custom"

./scripts/reload    ${host} gogs
