#!/usr/bin/env bash

source  ./scripts/_init.sh

INSTALL_ROOT=/home/git

./scripts/sync  ${EO_CONF}/gogs/custom/     ${EO_HOST}:${INSTALL_ROOT}/gogs/custom/

./scripts/run   ${EO_HOST}    <<EOF
    command -v systemctl > /dev/null 2>&1 && {
        systemctl   enable  ${INSTALL_ROOT}/gogs/scripts/systemd/gogs.service
    }
    command -v systemctl > /dev/null 2>&1 || {
        cp          -f      ${INSTALL_ROOT}/gogs/scripts/init/centos/gogs  /etc/init.d/
        chomod      755     /etc/init.d/gogs
    }
EOF

./scripts/reload    ${EO_HOST}  gogs
