#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
    DOWNLOAD_URL='http://7d9nal.com2.z0.glb.qiniucdn.com/gogs_v0.9.113_linux_amd64.tar.gz'
    echo ${2} | grep '\.tar\.gz$'   && {
        host=${1}
        DOWNLOAD_URL=${2}
    }
    echo ${1} | grep '\.tar\.gz$'   && {
        host=${EASY_OP_SSH_HOST}
        DOWNLOAD_URL=${1}
    }
fi

INSTALL_ROOT=/home/git

DWONLOAD_FILE=${DOWNLOAD_URL##*/}

ssh     ${host}    <<EOF
yum     install -y  git
id      -u      git >/dev/null  ||  useradd -m git
mkdir   -p      ${INSTALL_ROOT}
mkdir   -p      /data/gogs/data
mkdir   -p      /data/gogs/repo
mkdir   -p      /data/gogs/log
chown   -fR     git:git             /data/gogs
cd              ${INSTALL_ROOT}
curl    -o      ${DWONLOAD_FILE}    ${DOWNLOAD_URL}
rm      -rf     ${INSTALL_ROOT}/gogs
tar     -zxf    ${DWONLOAD_FILE}
EOF

./scripts/gogs/conf-update  ${host}
