#!/usr/bin/env bash

source  ./scripts/_init.sh

DOWNLOAD_URL=${1}
grep '\.tar\.gz$'   >/dev/null 2>&1   <<< "${DOWNLOAD_URL}"   || {
    DOWNLOAD_URL='http://7d9nal.com2.z0.glb.qiniucdn.com/gogs_v0.9.113_linux_amd64.tar.gz'
}

INSTALL_ROOT=/home/git

DWONLOAD_FILE=${DOWNLOAD_URL##*/}

./scripts/run   ${EO_HOST}  <<EOF
set     -e

yum     install -y  git
id      -u      git >/dev/null 2>&1  ||  useradd -m git
mkdir   -p      ${INSTALL_ROOT}
mkdir   -p      /data/gogs/data
mkdir   -p      /data/gogs/repo
mkdir   -p      /data/gogs/log
chown   -fR     git:git             /data/gogs
cd              ${INSTALL_ROOT}
curl    -o      ${DWONLOAD_FILE}    ${DOWNLOAD_URL}
rm      -rf     ${INSTALL_ROOT}/gogs
tar     -zxf    ${DWONLOAD_FILE}
EOF

./scripts/update-conf-and-reload    ${EO_HOST}  gogs
