#!/usr/bin/env bash

source  ./services/_init.sh

./services/run   ${EO_HOST} <<'EOF'
set -e
    command -v   rsync      >/dev/null 2>&1     ||  yum install -y rsync
    command -v   curl       >/dev/null 2>&1     ||  yum install -y curl

    rpm -q  epel-release    >/dev/null 2>&1     || yum install -y epel-release
    rpm -q  yum-utils       >/dev/null 2>&1     || yum install -y yum-utils
    rpm -q  yum-cron        >/dev/null 2>&1     || yum install -y yum-cron
EOF
