#!/usr/bin/env bash

source  ./scripts/_init.sh

client=${1}

easyrsa_dir=
for d in $(./scripts/run ${EO_HOST} find /usr/share/easy-rsa/ -mindepth 1 -maxdepth 1 -type d) ;do
    easyrsa_dir=$d
done
if [ "$easyrsa_dir" = "" ] ;then
    echo    ERROR: easy-rsa directory not found
else
    ./scripts/run   ${EO_HOST} "cd ${easyrsa_dir}; source vars;./build-key ${client}"
fi
