#!/usr/bin/env bash

set -e

if [ "${2}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
    client=${1}
else
    host=${1}
    client=${2}
fi

if [ -d servers/${host}/_secret/openvpn/${client} ] ;then
    rm  -rf servers/${host}/_secret/openvpn/${client}
fi
mkdir   -p  servers/${host}/_secret/openvpn/${client}
pushd   servers/${host}/_secret/openvpn/keys/    > /dev/null 2>&1
cp  ../../../openvpn/client.conf  ../${client}/${host}.ovpn
cp  ca.crt ta.key ${client}.crt ${client}.csr ${client}.key   ../${client}/
popd    > /dev/null 2>&1
