#!/usr/bin/env bash

source  ./scripts/_init.sh

client=${1}

if [ -d ${EO_CONF}/_secret/openvpn/${client} ] ;then
    rm  -rf ${EO_CONF}/_secret/openvpn/${client}
fi

mkdir   -p  ${EO_CONF}/_secret/openvpn/${client}
pushd   ${EO_CONF}/_secret/openvpn/keys/    > /dev/null 2>&1
cp  ../../../openvpn/client.conf  ../${client}/${EO_HOST}.ovpn
cp  ca.crt ta.key ${client}.crt ${client}.csr ${client}.key   ../${client}/
popd    > /dev/null 2>&1
