#!/usr/bin/env bash

source  ./scripts/_init.sh

easyrsa_dir=
for d in $(./scripts/run ${EO_HOST} find /usr/share/easy-rsa/ -mindepth 1 -maxdepth 1 -type d) ;do
    easyrsa_dir=$d
done
if [ "$easyrsa_dir" = "" ] ;then
    echo    ERROR: easy-rsa directory not found
else
    ./scripts/sync  ${EO_CONF}/openvpn/vars    ${EO_HOST}:$easyrsa_dir/
fi

./scripts/sync  ${EO_CONF}/openvpn/server.conf ${EO_HOST}:/etc/openvpn/


./scripts/reload    ${EO_HOST} openvpn
