#!/usr/bin/env bash

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

./scripts/run-script          ${host}   files/openvpn/install.sh
./scripts/openvpn/conf-update ${host}
./scripts/run-script          ${host}   files/openvpn/install.sh
