#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

easyrsa_dir=
for d in $(ssh ${host} find /usr/share/easy-rsa/ -mindepth 1 -maxdepth 1 -type d) ;do
    easyrsa_dir=$d
done
if [ "$easyrsa_dir" = "" ] ;then
    echo    ERROR: easy-rsa directory not found
else
    ssh ${host} "cd ${easyrsa_dir}; source vars;./clean-all"
    ./scripts/sync  servers/${host}/_secret/openvpn/keys/    ${host}:$easyrsa_dir/keys/
fi
