#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run                   ${EO_HOST}   <<'EOF'
#!/usr/bin/env bash

set -e

# enable forward
cat /etc/sysctl.conf | grep "net\\.ipv4\\.ip_forward[ \t]*=[ \t]*1" > /dev/null 2>&1 || {
    echo    net.ipv4.ip_forward = 1     >>  /etc/sysctl.conf
    sysctl  -p
}

# install openvpn
rpm -q  openvpn > /dev/null 2>&1     ||  {
    yum     install -y  openvpn easy-rsa
    # make cert
    easyrsa_dir=
    for d in $(find /usr/share/easy-rsa/ -mindepth 1 -maxdepth 1 -type d) ;do
        easyrsa_dir=$d
    done
    if [ -n "$easyrsa_dir" ] ;then
        if [ ! -d "${easyrsa_dir}/keys" ] ;then
            pushd   "$easyrsa_dir"
                source  vars
                ./clean-all
                ./pkitool --initca
                ./pkitool --server server
                ./build-dh
                openvpn --genkey --secret keys/ta.key
                cd keys &&  /usr/bin/cp -f dh2048.pem ca.crt server.crt server.key ta.key /etc/openvpn/
            popd
        fi
    fi
}

exit    0
EOF

./scripts/update-conf-and-reload    ${EO_HOST}  openvpn
