#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh ${host} <<EOF
#!/usr/bin/env bash

set -e

command -v systemctl > /dev/null 2>&1 && {
    systemctl   enable              openvpn@serverservice
    systemctl   reload-or-restart   openvpn@server.service
    echo        ----------------------
    systemctl   status              openvpn@server.service
}

command -v systemctl > /dev/null 2>&1 || {
    chkconfig   openvpn     on
    service     openvpn     reload
    echo        ----------------------
    service     openvpn     status
}

exit    0
EOF
