#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh ${host} <<EOF
#!/usr/bin/env bash

set -e

command -v systemctl > /dev/null 2>&1 && {
    systemctl   is-active   openvpn@server.service > /dev/null 2>&1   && {
        systemctl   stop    openvpn@server.service
    }
    systemctl   disable     openvpn@server.service
    echo        ----------------------
    systemctl   status      openvpn@server.service      ||  echo ''
}

command -v systemctl > /dev/null 2>&1   || {
    chkconfig   openvpn     off
    service     openvpn     stop
    echo        ----------------------
    service     openvpn     status      ||  echo ''
}

exit    0
EOF
