#!/usr/bin/env bash

source  ./scripts/_init.sh

EO_SVC=iptables

for conf_file in etc/sysconfig/iptables ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./scripts/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done
