#!/usr/bin/env bash

source  ./scripts/_init.sh

[ -f ${EO_CONF}/iptables/iptables ] &&
    ./scripts/sync  ${EO_CONF}/iptables/iptables  ${EO_HOST}:/etc/sysconfig/iptables

./scripts/reload    ${EO_HOST} iptables
