#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

./scripts/run-script   ${host}  files/iptables/install.sh

./scripts/iptables/conf-update ${host}
