#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    <<EOF
which systemctl > /dev/null && {
    systemctl   status  iptables.service > /dev/null   && {
        systemctl   stop    iptables.service
    }
    systemctl   disable  iptables.service
}
echo        ----------------------
systemctl   status  iptables.service
EOF
