#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    <<EOF
#!/usr/bin/env bash

set -e

which systemctl > /dev/null && {
    systemctl   is-active   iptables.service > /dev/null   && {
        systemctl   stop    iptables.service
    }
    systemctl   disable     iptables.service
    echo        ----------------------
    systemctl   status      iptables.service
}

which systemctl > /dev/null || {
    chkconfig   iptables    off
    service     iptables    stop
    echo        ----------------------
    service     iptables    status
}

exit    0
EOF
