#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run       ${EO_HOST}    <<'EOF'
    set     -e
    command -v      docker-compose  >/dev/null 2>&1 ||  {
        yum     list    installed   'python*-pip'   ||  yum install -y python-pip
        pip     install docker-compose
    }
    command -v      docker-compose  >/dev/null 2>&1 ||  {
        exit    1
    }
    exit    0
EOF

./scripts/update-conf   ${EO_HOST}  docker-compose
