#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh ${host} <<EOF
command -v   rsync   >/dev/null 2>&1   ||  yum install -y rsync
command -v   curl    >/dev/null 2>&1   ||  yum install -y curl
EOF
