#!/usr/bin/env bash

source  ./scripts/_init.sh

svc=${1}
shift

if [ -x ./scripts/${svc}/svc-install ] ; then
    ./scripts/${svc}/svc-install    "${EO_HOST}"    $@
else
    ./scripts/run                   "${EO_HOST}"    \
            "yum list installed ${svc} >/dev/null 2>&1  ||yum install -y ${svc}"
fi
