#!/usr/bin/env bash

source  ./scripts/_init.sh

svc=${1}
shift

if [ -x ./scripts/${svc}/svc-install ] ; then
    ./scripts/${svc}/svc-install        "${EO_HOST}"    $@
else
    ./scripts/run                       "${EO_HOST}"    <<EOF
    rpm -q ${svc} >/dev/null 2>&1  ||yum install -y ${svc}
EOF
    ./scripts/update-conf-and-reload    "${EO_HOST}"    ${svc}  $@
fi
