#!/usr/bin/env bash

source  ./scripts/_init.sh

svc=${1}

if [ -x ./scripts/${svc}/svc-reload ] ; then
    ./scripts/${svc}/svc-reload     ${EO_HOST}
else
    ./scripts/run                   ${EO_HOST}    <<EOF
#!/usr/bin/env bash

set -e

command -v systemctl > /dev/null 2>&1 && {
    systemctl is-enabled ${svc}.service > /dev/null 2>&1    || {
        systemctl   enable              ${svc}.service
    }
    systemctl is-active ${svc}.service > /dev/null 2>&1     && {
        systemctl   reload-or-restart   ${svc}.service
    }   ||  {
        systemctl   start               ${svc}.service
    }
    echo        ----------------------
    systemctl   status                  ${svc}.service      ||  echo ''
}
command -v systemctl > /dev/null 2>&1 || {
    chkconfig   ${svc}      on
    service     ${svc}      reload
    echo        ----------------------
    service     ${svc}      status      ||  echo ''
}

exit    0
EOF
fi
