#!/usr/bin/env bash

source  ./scripts/_init.sh

svc=${1}
shift

if [ -x ./scripts/${svc}/svc-restart ] ; then
    ./scripts/${svc}/svc-restart    ${EO_HOST}  $@
else
    ./scripts/run                   ${EO_HOST}  <<EOF
#!/usr/bin/env bash

set -e

command -v systemctl > /dev/null 2>&1 && {
    systemctl is-enabled ${svc}.service > /dev/null 2>&1    || {
        systemctl   enable      ${svc}.service
    }
    systemctl is-active ${svc}.service > /dev/null 2>&1     && {
        systemctl   restart     ${svc}.service
    }   ||  {
        systemctl   start       ${svc}.service
    }
    echo        ----------------------
    systemctl   status          ${svc}.service      ||  true
}
command -v systemctl > /dev/null 2>&1 || {
    chkconfig   ${svc}          on
    service     ${svc}          restart
    echo        ----------------------
    service     ${svc}          status      ||  true
}

exit    0
EOF
fi
