#!/usr/bin/env bash

set -e

if [ "${2}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
    svc=${1}
else
    host=${1}
    svc=${2}
fi

if [ -x scripts/${svc}/svc-stop ] ; then
    scripts/${svc}/svc-stop   ${host}
else
    ssh     ${host}    <<EOF
#!/usr/bin/env bash

set -e

command -v systemctl > /dev/null 2>&1 && {
    systemctl   is-active   ${svc}.service > /dev/null 2>&1   && {
        systemctl   stop    ${svc}.service
    }
    systemctl   disable ${svc}.service
    echo        ----------------------
    systemctl   status  ${svc}.service      ||  echo ''
}

command -v systemctl > /dev/null 2>&1 || {
    chkconfig   ${svc}  off
    service     ${svc}  stop
    echo        ----------------------
    service     ${svc}  status      ||  echo ''
}

exit    0
EOF
fi

exit    0
