#!/usr/bin/env bash

source  ./scripts/_init.sh

svc=${1}
shift

if [ -x ./scripts/${svc}/conf-update ] ; then
    ./scripts/${svc}/conf-update    "${EO_HOST}"    $@
else
    echo    "ERROR: [scripts/${svc}/conf-update] not found"
fi
