#!/usr/bin/env bash

source  ./services/_init.sh

EO_SVC=sshd

for conf_file in etc/ssh/{ssh_config, sshd_config} ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done
