#!/usr/bin/env bash

source  ./services/_init.sh

keyfile=${1}
shift

command -v ssh-copy-id > /dev/null 2>&1 || {
    echo    'ERROR: no ssh-copy-id found'
}
command -v ssh-copy-id > /dev/null 2>&1 && {
    ssh-copy-id -i "${keyfile}" -o PreferredAuthentications=password $@ ${EO_HOST}
}
