#!/usr/bin/env bash

source  ./services/_init.sh

EO_SVC=crond

for conf_file in etc/{crontab, cron.allow, cron.deny, anacrontab} ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done

for conf_dir in etc/cron.{d, hourly, daily, weekly, monthly} ; do
    if [ -d "${EO_CONF}/${EO_SVC}/${conf_dir}" ] ;then
        for conf_file in $(ls "${EO_CONF}/${EO_SVC}/${conf_dir}/") ; do
            if [ -f "${EO_CONF}/${EO_SVC}/${conf_dir}/${conf_file}" ] ;then
                ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_dir}/${conf_file}"  "${EO_HOST}:/${conf_dir}/${conf_file}"\
                    --exclude="dummy"
            fi
        done
    fi
done

for conf_dir in var/spool/cron ; do
    if [ -d "${EO_CONF}/${EO_SVC}/${conf_dir}" ] ;then
        ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_dir}/"  "${EO_HOST}:/${conf_dir}/" \
            --exclude="dummy"
    fi
done
