#!/usr/bin/env bash

source  ./services/_init.sh

EO_SVC=logrotate

for conf_file in etc/logrotate.conf ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done

for conf_dir in etc/logrotate.d ; do
    if [ -d "${EO_CONF}/${EO_SVC}/${conf_dir}" ] ;then
        for conf_file in $(ls "${EO_CONF}/${EO_SVC}/${conf_dir}/") ; do
            if [ -f "${EO_CONF}/${EO_SVC}/${conf_dir}/${conf_file}" ] ;then
                ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_dir}/${conf_file}"  "${EO_HOST}:/${conf_dir}/${conf_file}"\
                    --exclude="dummy"
            fi
        done
    fi
done
