#!/usr/bin/env bash

source  ./services/_init.sh

EO_SVC=etc

for conf_dir in etc ; do
    mkdir   -p      "${EO_CONF}/_backup/${conf_dir}/"
    ./services/sync  "${EO_HOST}:/${conf_dir}/"    "${EO_CONF}/_backup/${conf_dir}/"
done
