#!/usr/bin/env bash

source  ./services/_init.sh

EO_SVC=etc

for conf_file in etc/hosts.allow  etc/hosts.deny ; do
    if [ -f "${EO_CONF}/${EO_SVC}/${conf_file}" ] ;then
        ./services/sync  "${EO_CONF}/${EO_SVC}/${conf_file}"  "${EO_HOST}:/${conf_file}"
    fi
done
