#!/usr/bin/env bash

set -e

if [ "${2}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
    keyfile=${1}
    shift
else
    host=${1}
    shift
    keyfile=${1}
    shift
fi

which ssh-copy-id > /dev/null || {
    echo    'ERROR: no ssh-copy-id found'
}
which ssh-copy-id > /dev/null && {
    ssh-copy-id -i "${keyfile}" -o PreferredAuthentications=password $@ ${host}
}
