#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run   ${EO_HOST}  'yum list installed sshd >/dev/null 2>&1 || yum install -y  sshd'

./scripts/sshd/conf-update  ${EO_HOST}
./scripts/reload            ${EO_HOST}  sshd
