#!/usr/bin/env bash

source  ./services/_init.sh

if [[ ${1} = '' ]]; then
    ./services/run   ${EO_HOST}     <<'EOF'
        for table in $(nscd -g| grep 'cache:'| cut -d ' ' -f 1); do
            nscd    -i  ${table}
        done
EOF
else
    ./services/run   ${EO_HOST} "nscd    -i  ${1}"
fi
