#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

CONF_DIR=/etc/openresty

./scripts/sync  servers/${host}/openresty/conf/      ${host}:${CONF_DIR}/conf/

# start service
ssh     ${host}    <<EOF
which systemctl > /dev/null 2>&1 && {
    systemctl   enable      ${CONF_DIR}/service/openresty.service
}
which systemctl > /dev/null 2>&1 || {
    cp          -f          ${CONF_DIR}/service/openresty  /etc/init.d/
    chomod      755         /etc/init.d/openresty
}
EOF

./scripts/svc/reload    ${host} openresty
