#!/usr/bin/env bash

source  ./scripts/_init.sh

CONF_DIR=/etc/openresty

./scripts/sync  ${EO_CONF}/openresty/conf/      ${EO_HOST}:${CONF_DIR}/conf/

# start service
./scripts/run       ${EO_HOST}    <<EOF
    command -v systemctl > /dev/null 2>&1 && {
        systemctl   enable      ${CONF_DIR}/service/openresty.service
    }
    command -v systemctl > /dev/null 2>&1 || {
        cp          -f          ${CONF_DIR}/service/openresty  /etc/init.d/
        chomod      755         /etc/init.d/openresty
    }
EOF

./scripts/reload    ${EO_HOST} openresty
