#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh     ${host}    '
set -e

id      -u      nginx >/dev/null    ||  useradd -M -s /bin/nologin nginx

yum repolist enabled    |   grep "Official OpenResty Repository" > /dev/null    || {
    yum info    installed   yum-utils > /dev/null    ||
        yum     install -y  yum-utils
    yum-config-manager --add-repo https://openresty.org/yum/centos/OpenResty.repo
}

yum --disablerepo="*" --enablerepo="openresty"  info installed openresty > /dev/null    ||
    yum --disablerepo="*" --enablerepo="openresty"  install -y openresty

mkdir   -p      /data/openresty/service
'

./scripts/sync  files/openresty/service/     ${host}://data/openresty/service/

./scripts/openresty/conf-update     ${host}
