#!/usr/bin/env bash

source  ./scripts/_init.sh

CONF_DIR=/etc/openresty

./scripts/run   ${EO_HOST}    <<EOF
set -e

id      -u      nginx >/dev/null 2>&1    ||  useradd -M -s /sbin/nologin nginx

yum repolist enabled    |   grep "Official OpenResty Repository" > /dev/null 2>&1    || {
    yum info    installed   yum-utils > /dev/null 2>&1    ||
        yum     install -y  yum-utils
    yum-config-manager --add-repo https://openresty.org/yum/centos/OpenResty.repo
}

yum --disablerepo="*" --enablerepo="openresty"  info installed openresty > /dev/null 2>&1    ||
    yum --disablerepo="*" --enablerepo="openresty"  install -y openresty

mkdir   -p      ${CONF_DIR}/service
EOF

./scripts/sync  files/openresty/service/     ${EO_HOST}:${CONF_DIR}/service/

./scripts/openresty/conf-update     ${EO_HOST}
