#!/usr/bin/env bash

source  ./scripts/_init.sh

BOT_ROOT=${1}
BOT_NAME=${BOT_ROOT##*/}

./scripts/run   ${EO_HOST}  <<EOF
set -e
rpm     -q  npm > /dev/null 2>&1 ||  yum install -y  npm
command -v  npm > /dev/null 2>&1 || {
    yum install -y  npm
}
command -v  npm > /dev/null 2>&1 && {
    mkdir   -p      ~/.config
    chmod   g+rwx   ~/.config

    mkdir   -p      ~/.npm
    chmod   g+rwx   ~/.npm

    npm update  -g  n
    npm install -g  coffee-script yo generator-hubot
}
EOF

./scripts/update-conf   ${EO_HOST}  hubot
