#!/usr/bin/env bash

set -e

if [ "${1}" = "" ] ;then
    host=${EASY_OP_SSH_HOST}
else
    host=${1}
fi

ssh   ${host}  'yum list installed ntp >/dev/null 2>&1 || yum install -y  ntp'

./scripts/ntpd/conf-update ${host}
