#!/usr/bin/env bash

source  ./scripts/_init.sh

./scripts/run   ${EO_HOST}  <<EOF
set -e
rpm     -q  npm > /dev/null 2>&1 ||  yum install -y  npm
command -v  npm > /dev/null 2>&1 || {
    yum install -y  npm
}
command -v  npm > /dev/null 2>&1 && {
    npm update  -g  n
}
EOF
